page_login/urls.py
from django.conf.urls import url
from .views import *

from .custom_auth import auth_login, auth_logout

urlpatterns = [
    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    # index dan dashboard
    url(r'^$', index, name='index'),
]

tp02/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import page_profile.urls as page_profile
import page_login.urls as page_login
import page_status.urls as page_status
import page_riwayat.urls as page_riwayat
import page_carimahasiswa.urls as page_carimahasiswa

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^page_login/', include(page_login,namespace='page_login')),
    url(r'^page_status/', include(page_status,namespace='page_status')),
    url(r'^page_profile/', include(page_profile,namespace='page_profile')),
    url(r'^page_riwayat/', include(page_riwayat,namespace='page_riwayat')),
    url(r'^page_carimahasiswa/', include(page_carimahasiswa,namespace='page_carimahasiswa')),
    url(r'^$', RedirectView.as_view(url='page_login/', permanent=True), name='first'),
]

page_login/models.py
from django.db import models

# Create your models here.

page_login/views.py
from django.shortcuts import render

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from page_status.tambahan import get_data_user
response = {}
# Create your views here.
def index(request):
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('page_status:index'))
    else:
        response['author'] = get_data_user(request, 'user_login')
        html = 'page_login/page_login.html'
        return render(request, html, response)

page_login/templates/page_login/page_login.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="background: linear-gradient(to right, 	#7b88b8, 	#d8a5a0	); font-size: 18px;">
      <div class="col-md-6 col-md-offset-3" style="text-align:center">
          <div class="rata-tengah">
              <div class="judul">
                  <h1 > LOGIN </h1>
                  <p class="text-info"> Gunakan <b> akun SSO </p>
              </div><br>
              <form action="{% url 'page_login:auth_login' %}" method="POST">
                  {% csrf_token %}
                  <p>
                      <label for="username"> Your username </label>
                      <input type="text" id="username" name="username" required>
                  </p>
                  <p>
                      <label for="password"> Your password </label>
                      <input type="password" id="password" name="password" required>
                  </p>
                  <input type="submit" class="btn btn-primary">
              </form>
          </div>
      </div>
</div><br>
{% endblock %}