page_login/urls.py
from django.conf.urls import url
from .views import *

from .custom_auth import auth_login, auth_logout

urlpatterns = [
    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    # index dan dashboard
    url(r'^$', index, name='index'),
]

page_profile/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [

    url(r'^edit_profile/$', edit_profile, name='edit_profile'),
    url(r'^save_to_database/$', save_to_database, name='save_to_database'),
    url(r'^$', index, name='index'),
]

page_status/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'add_status/$', add_status, name='add_status'),
]

tp02/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import page_profile.urls as page_profile
import page_login.urls as page_login
import page_status.urls as page_status
import page_riwayat.urls as page_riwayat
import page_carimahasiswa.urls as page_carimahasiswa

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^page_login/', include(page_login,namespace='page_login')),
    url(r'^page_status/', include(page_status,namespace='page_status')),
    url(r'^page_profile/', include(page_profile,namespace='page_profile')),
    url(r'^page_riwayat/', include(page_riwayat,namespace='page_riwayat')),
    url(r'^page_carimahasiswa/', include(page_carimahasiswa,namespace='page_carimahasiswa')),
    url(r'^$', RedirectView.as_view(url='page_login/', permanent=True), name='first'),
]

page_status/models.py
from __future__ import unicode_literals
from django.db import models

class Pengguna(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, )
    nama = models.CharField('Nama', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    
class Update(models.Model):
    pengguna = models.ForeignKey(Pengguna)
    created_at = models.DateTimeField(auto_now_add=True)
    activity = models.TextField()

page_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    description_attrs = {
        'type': 'text',
        'cols': 80,
        'rows': 10,
        'class': 'update-form-textarea',
        'placeholder':'Whats on your mind?'
    }

    activity = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

page_status/views.py
from django.shortcuts import render

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from page_riwayat.api_riwayat import get_matkul
from page_profile.views import index
from page_profile.models import User
from .models import Update, Pengguna
from .forms import Status_Form
from .tambahan import *

response = {}

# Create your views here.
def index(request):
    if 'user_login' not in request.session.keys():
        return HttpResponseRedirect(reverse('page_login:index'))
    else:
        set_data_for_session(response , request)
        kode_identitas = get_data_user(request, 'kode_identitas')
        try:
            pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
        except Exception as e:
            pengguna = create_new_user(request)

        list_status = get_status_from_session(request)
        save_status_to_database(pengguna, list_status)
        
        pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
        response['status'] = pengguna.update_set.all().order_by('-id')
        response['jstat'] = pengguna.update_set.count()

        stat = pengguna.update_set.all().order_by('-id')
        if(len(stat) > 0):
            message = stat[0]
            newMessage = message.activity
            time = message.created_at
        else:
            newMessage = 'message not available'
            
        response['lastStatus']= newMessage
        response['matkuls'] = get_matkul().json()
        users = User.objects.all()
        response['users'] = users
        npm = request.session['kode_identitas']
        user = (User.objects.filter(kode_identitas=npm)
                             .values('firstName', 'lastName','imageUrl',
                             'email','profileUrl','kode_identitas','angkatan'))
        if(user):
            response['user'] = user[0]
        html = 'page_status/page_status.html'
        return render(request, html, response)

def get_data_session(request):
    if get_data_user(request, 'user_login'):
        response['author'] = get_data_user(request, 'user_login')
        
def set_data_for_session(response, request):
    response['author'] = request.session['user_login']
    response['access_token'] = request.session['access_token']
    response['kode_identitas'] = request.session['kode_identitas']
    response['role'] = request.session['role']
    response['update_form'] = Status_Form

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        suatuTulisan = request.POST['activity']
        if get_data_user(request, 'user_login'):
            print("TO DB")
            is_in_db = check_status_in_database(request, suatuTulisan)
            if not is_in_db:
                add_status_to_database(request, suatuTulisan)
        else:
            print("TO SESSION")
            is_in_ssn = check_status_in_session(request, suatuTulisan)
            if not is_in_ssn:
                add_status_to_session(request, suatuTulisan)

    return HttpResponseRedirect(reverse('page_status:index'))
        
def list_status(request):
    status = []
    if get_data_user(request, 'user_login'):
        status = get_my_status_from_database(request)
    else:
        status = get_my_status_from_session(request)

    response['status'] = status
    html = 'page_status/status.html'
    return render(request, html, response)

page_status/templates/page_status/page_status.html
{% extends "base.html" %}

<!-- Content Here -->
{% block header %}
<div class="navbar navbar-default" role="navigation" style="background: #d8a5a0;">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span> 
                        <strong>{{author}}</strong>
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="navbar-login">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <h4 class="text-center"><strong>{{author}}</strong></h4>
                                        <h4 class="text-center small">NPM: {{kode_identitas}}</h4>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="navbar-login navbar-login-session">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <p>
                                            <a href="{% url 'page_login:auth_logout' %}" class="btn btn-danger btn-block" onclick="return confirm('Keluar?')">
                                                Logout </a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock%}

{% block content %}
<div class="pojok-kanan">
</div>
<br>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2> Profile </h2>
    </div>
    <div class="panel-body" style="font-weight:bold; font-size: 18px; background: linear-gradient(to right, 	#7b88b8, 	#d8a5a0	);">
        <p> Username : {{ author }} </p>
        <p> NPM : {{kode_identitas}} </p>
        <p> Role : {{ role }} </p>
        <p> Jumlah Status: {{jstat}} </p>
        <p> Last Status: {{lastStatus}} </p>
    </div>
    <div class="panel-footer">
       <a href="{% url 'page_profile:edit_profile' %}" class="btn btn-info" > Edit Profile </a>
       <a href="{% url 'page_login:auth_logout' %}" class="btn btn-danger" onclick="return confirm('Keluar?')">Logout </a>
   </div>

</div>

<div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
        <li role="presentation" class="active">
            <a href="#profile" aria-controls="home" role="tab" data-toggle="tab"> Profile </a>
        </li>
        <li role="presentation">
            <a href="#riwayat" aria-controls="settings" role="tab" data-toggle="tab"> Riwayat </a>
        </li>
        <li role="presentation">
            <a href="#status" aria-controls="settings" role="tab" data-toggle="tab"> Status </a>
        </li>
        <li role="presentation">
            <a href="#teman" aria-controls="settings" role="tab" data-toggle="tab"> Teman </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="profile">
            {% include 'page_profile/page_profile.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="riwayat">
            {% include 'page_riwayat/riwayat.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="teman">
            {% include 'page_carimahasiswa/page_carimahasiswa.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="status">
            {% include 'page_status/status.html' %}
        </div>
    </div>
</div>
{% endblock %}

page_status/templates/page_status/status.html
{% load staticfiles %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/page_status.css' %}" />
<h2 class="main-title" style="font-weight:bold; font-size: 50px; text-align:center"> Status </h2>
<hr/>

<div name="update-list" id="update-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'page_status:add_status' %}">
            {% csrf_token %}
            {{ update_form }}
            <input  id="submit" type="submit" class="btn btn-secondary float-right" value="POST">
            <br>
        </form>
    </div>
</div>

<div name="update-status" id="update-status">
    {% for data in status %}
      <div class = "status">
            <div class="row">
              <div class="col-sm-12 col-sm-offset-0">
                <div class="media" style="padding: 15px">
                  <div class="media-body">
                    <strong>{{user_name}}</strong>
                    <p>{{data.activity}}</p>
                    <i>Posted on {{data.created_at}}</i>
                  </div>
                </div>
              </div>
            </div>
          </div>
    {% endfor %}
</div>
<hr/>